// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("customers")]
[Index("IdentificationTypeId", Name = "IX_customers_identification_type_id")]
public partial class Customer
{
    [Key]
    [Column("customer_id")]
    public int CustomerId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Column("identification_type_id")]
    public int IdentificationTypeId { get; set; }

    [Required]
    [Column("identification_number")]
    [StringLength(20)]
    public string IdentificationNumber { get; set; }

    [Column("email")]
    [StringLength(150)]
    public string Email { get; set; }

    [Column("phone")]
    [StringLength(15)]
    public string Phone { get; set; }

    [Column("address")]
    public string Address { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [ForeignKey("IdentificationTypeId")]
    [InverseProperty("Customers")]
    public virtual IdentificationType IdentificationType { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}