// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("device_types")]
[Index("Name", Name = "UQ_device_types_name", IsUnique = true)]
public partial class DeviceType
{
    [Key]
    [Column("device_type_id")]
    public int? DeviceTypeId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [InverseProperty("DeviceType")]
    public virtual ICollection<Model> Models { get; set; } = new List<Model>();
}