// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("email_templates")]
public partial class EmailTemplate
{
    [Key]
    [Column("template_id")]
    public int TemplateId { get; set; }

    [Required]
    [Column("description")]
    [StringLength(100)]
    public string Description { get; set; }

    [Required]
    [Column("subject")]
    [StringLength(150)]
    public string Subject { get; set; }

    [Required]
    [Column("body")]
    public string Body { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [InverseProperty("Template")]
    public virtual ICollection<EmailConfig> EmailConfigs { get; set; } = new List<EmailConfig>();
}