// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("email_configs")]
[Index("TemplateId", Name = "IX_email_configs_template_id")]
[Index("UserId", Name = "IX_email_configs_user_id")]
public partial class EmailConfig
{
    [Key]
    [Column("config_id")]
    public int ConfigId { get; set; }

    [Column("user_id")]
    public int? UserId { get; set; }

    [Required]
    [Column("sender")]
    [StringLength(150)]
    public string Sender { get; set; }

    [Column("cc_addresses")]
    public string CcAddresses { get; set; }

    [Column("cco_addresses")]
    public string CcoAddresses { get; set; }

    [Column("template_id")]
    public int TemplateId { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [ForeignKey("TemplateId")]
    [InverseProperty("EmailConfigs")]
    public virtual EmailTemplate Template { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("EmailConfigs")]
    public virtual User User { get; set; }
}