// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("identification_types")]
[Index("Name", Name = "UQ_identification_types_name", IsUnique = true)]
public partial class IdentificationType
{
    [Key]
    [Column("identification_type_id")]
    public int IdentificationTypeId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [InverseProperty("IdentificationType")]
    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
}