// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("item_statuses")]
[Index("Name", Name = "UQ_item_statuses_name", IsUnique = true)]
public partial class ItemStatus
{
    [Key]
    [Column("item_status_id")]
    public int ItemStatusId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [InverseProperty("ItemStatus")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}