// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("models")]
[Index("BrandId", Name = "IX_models_brand_id")]
[Index("DeviceTypeId", Name = "IX_models_device_type_id")]
public partial class Model
{
    [Key]
    [Column("model_id")]
    public int ModelId { get; set; }

    [Column("brand_id")]
    public int BrandId { get; set; }

    [Column("device_type_id")]
    public int DeviceTypeId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [ForeignKey("BrandId")]
    [InverseProperty("Models")]
    public virtual Brand Brand { get; set; }

    [ForeignKey("DeviceTypeId")]
    [InverseProperty("Models")]
    public virtual DeviceType DeviceType { get; set; }

    [InverseProperty("Model")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}