// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("orders")]
[Index("CustomerId", Name = "IX_orders_customer_id")]
[Index("OrderStatusId", Name = "IX_orders_order_status_id")]
[Index("RequestedBy", Name = "IX_orders_requested_by")]
public partial class Order
{
    [Key]
    [Column("order_id")]
    public int OrderId { get; set; }

    [Column("customer_id")]
    public int CustomerId { get; set; }

    [Column("requested_by")]
    public int RequestedBy { get; set; }

    [Column("order_status_id")]
    public int OrderStatusId { get; set; }

    [Column("scheduled_for")]
    public DateTime? ScheduledFor { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("date_update", TypeName = "datetime")]
    public DateTime? DateUpdate { get; set; }

    [Column("user_update")]
    public int? UserUpdate { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [ForeignKey("CustomerId")]
    [InverseProperty("Orders")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderAssignment> OrderAssignments { get; set; } = new List<OrderAssignment>();

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("OrderStatusId")]
    [InverseProperty("Orders")]
    public virtual OrderStatus OrderStatus { get; set; }

    [ForeignKey("RequestedBy")]
    [InverseProperty("Orders")]
    public virtual User RequestedByNavigation { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<Solution> Solutions { get; set; } = new List<Solution>();
}