// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("order_assignments")]
[Index("OrderId", Name = "IX_order_assignments_order_id")]
[Index("TechnicianId", Name = "IX_order_assignments_technician_id")]
public partial class OrderAssignment
{
    [Key]
    [Column("assignment_id")]
    public int AssignmentId { get; set; }

    [Column("order_id")]
    public int OrderId { get; set; }

    [Column("technician_id")]
    public int? TechnicianId { get; set; }

    [Column("assigned_at")]
    public DateTime AssignedAt { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderAssignments")]
    public virtual Order Order { get; set; }

    [ForeignKey("TechnicianId")]
    [InverseProperty("OrderAssignments")]
    public virtual User Technician { get; set; }
}