// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("order_details")]
[Index("ItemStatusId", Name = "IX_order_details_item_status_id")]
[Index("ModelId", Name = "IX_order_details_model_id")]
[Index("OrderId", Name = "IX_order_details_order_id")]
public partial class OrderDetail
{
    [Key]
    [Column("detail_id")]
    public int DetailId { get; set; }

    [Column("order_id")]
    public int OrderId { get; set; }

    [Column("model_id")]
    public int ModelId { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("intake_photo")]
    public string IntakePhoto { get; set; }

    [Column("item_status_id")]
    public int ItemStatusId { get; set; }

    [Column("device_specs")]
    public string DeviceSpecs { get; set; }

    [ForeignKey("ItemStatusId")]
    [InverseProperty("OrderDetails")]
    public virtual ItemStatus ItemStatus { get; set; }

    [ForeignKey("ModelId")]
    [InverseProperty("OrderDetails")]
    public virtual Model Model { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }
}