// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Adarec.Domain.Models.Entities;

[Table("solutions")]
[Index("OrderId", Name = "IX_solutions_order_id")]
public partial class Solution
{
    [Key]
    [Column("solution_id")]
    public int SolutionId { get; set; }

    [Column("order_id")]
    public int OrderId { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("final_photo")]
    public string FinalPhoto { get; set; }

    [Column("closed_at")]
    public DateTime ClosedAt { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Solutions")]
    public virtual Order Order { get; set; }
}